final products = [
  {
    'id': '0',
    'title': 'Men\'s New Balance Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'New Balance',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '1',
    'title': 'Adidas Shoes',
    'price': 20.12,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Adidas',
    'sizes': [9, 10, 12],
  },
  {
    'id': '2',
    'title': 'Nike Women\'s Shoes',
    'price': 28.95,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': '3',
    'title': 'Jordan Shoes',
    'price': 420.69,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Jordan',
    'sizes': [8, 9, 10],
  },
  {
    'id': '4',
    'title': 'Rick Owens Shoes',
    'price': 28.95,
    'imageUrl': 'assets/images/shoes_5.jpeg',
    'company': 'Rick Owens',
    'sizes': [8, 9, 10],
  },
];
